# Generated by Django 5.0.2 on 2024-10-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("role", models.CharField(max_length=50)),
                ("permissions", models.TextField()),
                ("password_hash", models.CharField(max_length=128)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
