# Generated by Django 4.0 on 2024-10-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_blacklistedtoken_remove_user_permissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_hash',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=23, max_length=255),
            preserve_default=False,
        ),
    ]
