# Generated by Django 5.0.2 on 2024-10-18 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Machine",
            fields=[
                ("machine_id", models.AutoField(primary_key=True, serialize=False)),
                ("machine_name", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=50)),
                ("status", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=100)),
                ("last_maintenance_date", models.DateField()),
                ("next_maintenance_due", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Production",
            fields=[
                ("production_id", models.AutoField(primary_key=True, serialize=False)),
                ("shift", models.CharField(max_length=50)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("units_produced", models.IntegerField()),
                ("defects", models.IntegerField()),
                ("status", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EnergyUsage",
            fields=[
                ("usage_id", models.AutoField(primary_key=True, serialize=False)),
                ("shift", models.CharField(max_length=50)),
                ("energy_consumed", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Machine.machine",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DefectLog",
            fields=[
                ("defect_id", models.AutoField(primary_key=True, serialize=False)),
                ("time_detected", models.DateTimeField(auto_now_add=True)),
                ("defect_type", models.CharField(max_length=100)),
                ("resolved", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Machine.machine",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MachineSensor",
            fields=[
                ("sensor_id", models.AutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=50)),
                ("threshold_values", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Machine.machine",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("task_id", models.AutoField(primary_key=True, serialize=False)),
                ("task_type", models.CharField(max_length=50)),
                ("due_date", models.DateTimeField()),
                ("status", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="User.user"
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Machine.machine",
                    ),
                ),
            ],
        ),
    ]
