# Generated by Django 5.1.2 on 2024-10-18 16:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Machine", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="machinesensor",
            name="machine",
        ),
        migrations.RenameField(
            model_name="defectlog",
            old_name="machine",
            new_name="id_machine",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="assigned_to",
            new_name="assignee",
        ),
        migrations.RemoveField(
            model_name="defectlog",
            name="timestamp",
        ),
        migrations.RemoveField(
            model_name="machine",
            name="location",
        ),
        migrations.RemoveField(
            model_name="machine",
            name="machine_name",
        ),
        migrations.RemoveField(
            model_name="machine",
            name="next_maintenance_due",
        ),
        migrations.RemoveField(
            model_name="production",
            name="defects",
        ),
        migrations.RemoveField(
            model_name="production",
            name="shift",
        ),
        migrations.RemoveField(
            model_name="production",
            name="status",
        ),
        migrations.RemoveField(
            model_name="production",
            name="units_produced",
        ),
        migrations.RemoveField(
            model_name="task",
            name="task_type",
        ),
        migrations.AddField(
            model_name="defectlog",
            name="production_id",
            field=models.ForeignKey(
                default=15,
                on_delete=django.db.models.deletion.CASCADE,
                to="Machine.production",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="production",
            name="energy_consumed",
            field=models.FloatField(
                default=10, validators=[django.core.validators.MinValueValidator(0.0)]
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="production",
            name="machin_id",
            field=models.ForeignKey(
                default=13,
                on_delete=django.db.models.deletion.CASCADE,
                to="Machine.machine",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="defect_id",
            field=models.ForeignKey(
                default=14,
                on_delete=django.db.models.deletion.CASCADE,
                to="Machine.defectlog",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="production",
            name="production_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.DeleteModel(
            name="EnergyUsage",
        ),
        migrations.DeleteModel(
            name="MachineSensor",
        ),
    ]
